### PR TITLE
[WIP] Migrate to Swift 4.1

### PR DESCRIPTION
**Pull request by NachoSoto**
### TODO:

- [x] Deal with `IndexDistance` deprecation (it's always `Int` now)
- [ ] Deal with other deprecation warnings
- [x] Wait for compiler crash (I found https://bugs.swift.org/browse/SR-6797 while working on this).
- [x] Tests passing
- [ ] Wait for `Xcode 9.3`
- [ ] Update `.travis.yml`

### CODE REVIEW

**Comment by NachoSoto** [comment]
Crash is fixed in beta 2, so tests are passing now with Xcode 4.1 :)

**Comment by fatlazycat** [comment]
Hi, any update to when this will be merged ? Thanks

**Comment by nvzqz** [comment]
@NachoSoto when do you think you'll be able to get this from WIP to working? If it's too long, I can just merge this and implement the remaining necessary changes? I can do so this Wednesday (4/4).

@fatlazycat thanks for the reminder!

**Comment by NachoSoto** [comment]
I won't be able to continue for a while, so feel free to pick it up from here.

**Comment by buscarini** [comment]
Can this be merged now that swift 4.1 has been released?

**Comment by fatlazycat** [comment]
Thanks, seen the merge. Is the version number going to get bumped ? Not entirely sure how Carthage find's updates.

**Comment by nvzqz** [comment]
I'll make a new tag and release sometime today. For now you can just use the master branch directly.

**Comment by fatlazycat** [comment]
Appears not to build under MacOS

https://gist.github.com/fatlazycat/53bbb8778236cc102bdca5bbde64e298

[carthage-xcodebuild.LbsrRV.log](https://github.com/nvzqz/RandomKit/files/1880224/carthage-xcodebuild.LbsrRV.log)

**Comment by fatlazycat** [comment]
Appear stop be an issue with 
`#if swift(>=4.1)` in Extensions/Swift/Collection+RandomKit.swift in the wrong place, should be a function above.

Then there is some issue with the build, from what I can workout it's building for the wrong version of swift. I think. If I remove the non 4.1 code mentioned above then it builds fine.

**Comment by fatlazycat** [comment]
had to fork and change the swift version in Xcode for carthage to build correctly.

**Pull request merged**
