### PR TITLE
Remove Foundation import from test class DistributionMoment

### PR DESCRIPTION
**Pull request by phimage**
& Add setup in unit test (allow to change random generator)

### CODE REVIEW

**Comment by nvzqz** [comment]
What's the point of assigning `RandomGenerator.default` to itself in `setUp()`?

**Comment by phimage** [comment]
the aim is test others generators manually and fastly, just by editing this line

unfortunately there is no parametrized unit tests in Xcode (like JUnit in java) well integrated
first I change all call of "random" functions by adding: "using: the_generator_as_test_class_var"
then I conclude that only change the default one do the same things

Maybe there is others solutions to test with all generators without make bad code copy

**Comment by nvzqz** [comment]
The tests are slow as it is with the fastest generator (default). I don't think it would be a good idea to have it test all generators at once.

Subclassing `RandomKitTests` seems to be the most reasonable way of going about it but I'd rather not for the sake of speed.

**Comment by nvzqz** [comment]
Implemented these same changes (33033677cbe6a6921a98c6d2b014afe194f6835c and 5030709dd0bf3ee88d2b67c28c37f3c01829bbbd) to be compatible with 6724e7a3e77f86c0ad81667d3b3df480c19b47f0 and 8d097fb6f5829623e42a5a92de261de6e044fc64.

**Pull request closed without merging**
